In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Display all columns
pd.set_option('display.max_columns', None)

In [4]:
df = pd.read_csv(r"C:\Users\PUNEET\OneDrive\Desktop\deeedidy\github\HR_newwwwwwwwwwwwwwwwwwwwwww\HR_Analytics_Cleaned_Master.csv")

In [34]:
df.shape

(4327, 31)

In [5]:
df.head()

,Age,Attrition,BusinessTravel,Department,DistanceFromHome,Education,EducationField,EmployeeID,Gender,JobLevel,JobRole,MaritalStatus,MonthlyIncome,NumCompaniesWorked,PercentSalaryHike,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,YearsAtCompany,YearsSinceLastPromotion,YearsWithCurrManager,EnvironmentSatisfaction,JobSatisfaction,WorkLifeBalance,JobInvolvement,PerformanceRating,Education_Label,JobSatisfaction_Label,EnvironmentSatisfaction_Label,WorkLifeBalance_Label,PerformanceRating_Label
0,51,No,Travel_Rarely,Sales,6,2,Life Sciences,1,Female,1,Healthcare Representative,Married,131160,1.0,11,0,1.0,6,1,0,0,3.0,4.0,2.0,3,3,College,Very High,High,Good,Excellent
1,31,Yes,Travel_Frequently,Research & Development,10,1,Life Sciences,2,Female,1,Research Scientist,Single,41890,0.0,23,1,6.0,3,5,1,4,3.0,2.0,4.0,2,4,Below College,Medium,High,Best,Outstanding
2,32,No,Travel_Frequently,Research & Development,17,4,Other,3,Male,4,Sales Executive,Married,193280,1.0,15,3,5.0,2,5,0,3,2.0,2.0,1.0,3,3,Master,Medium,Medium,Bad,Excellent
3,38,No,Non-Travel,Research & Development,2,5,Life Sciences,4,Male,3,Human Resources,Married,83210,3.0,11,3,13.0,5,8,7,5,4.0,4.0,3.0,2,3,Doctor,Very High,Very High,Better,Excellent
4,32,No,Travel_Rarely,Research & Development,10,1,Medical,5,Male,1,Sales Executive,Single,23420,4.0,12,2,9.0,2,6,0,4,4.0,1.0,3.0,3,3,Below College,Low,Very High,Better,Excellent

In [13]:
df.sample(5)

,Age,Attrition,BusinessTravel,Department,DistanceFromHome,Education,EducationField,EmployeeID,Gender,JobLevel,JobRole,MaritalStatus,MonthlyIncome,NumCompaniesWorked,PercentSalaryHike,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,YearsAtCompany,YearsSinceLastPromotion,YearsWithCurrManager,EnvironmentSatisfaction,JobSatisfaction,WorkLifeBalance,JobInvolvement,PerformanceRating,Education_Label,JobSatisfaction_Label,EnvironmentSatisfaction_Label,WorkLifeBalance_Label,PerformanceRating_Label
3379,50,No,Travel_Rarely,Research & Development,5,4,Life Sciences,3449,Male,1,Sales Executive,Married,118780,2.0,13,1,29.0,2,8,7,7,2.0,3.0,2.0,3,3,Master,High,Medium,Good,Excellent
4255,53,No,Travel_Rarely,Sales,1,2,Life Sciences,4337,Male,1,Manager,Divorced,39890,1.0,13,0,5.0,2,4,1,3,4.0,1.0,3.0,3,3,College,Low,Very High,Better,Excellent
2467,26,No,Travel_Rarely,Sales,8,3,Marketing,2522,Female,1,Healthcare Representative,Single,30330,1.0,12,0,5.0,2,5,1,2,3.0,4.0,3.0,2,3,Bachelor,Very High,High,Better,Excellent
3696,34,No,Travel_Rarely,Sales,25,5,Marketing,3770,Female,1,Research Scientist,Married,41940,0.0,17,2,12.0,3,11,5,7,2.0,3.0,3.0,3,3,Doctor,High,Medium,Better,Excellent
3262,35,No,Travel_Rarely,Research & Development,1,3,Life Sciences,3330,Male,3,Healthcare Representative,Married,167920,3.0,12,1,16.0,3,13,4,8,4.0,2.0,3.0,4,3,Bachelor,Medium,Very High,Better,Excellent

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4327 entries, 0 to 4326
Data columns (total 31 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Age                            4327 non-null   int64
 1   Attrition                      4327 non-null   object
 2   BusinessTravel                 4327 non-null   object
 3   Department                     4327 non-null   object
 4   DistanceFromHome               4327 non-null   int64
 5   Education                      4327 non-null   int64
 6   EducationField                 4327 non-null   object
 7   EmployeeID                     4327 non-null   int64
 8   Gender                         4327 non-null   object
 9   JobLevel                       4327 non-null   int64
 10  JobRole                        4327 non-null   object
 11  MaritalStatus                  4327 non-null   object
 12  MonthlyIncome                  4327 non-null   int64
 13  NumCompaniesWorked             4327 non-null   float64
 14  PercentSalaryHike              4327 non-null   int64
 15  StockOptionLevel               4327 non-null   int64
 16  TotalWorkingYears              4327 non-null   float64
 17  TrainingTimesLastYear          4327 non-null   int64
 18  YearsAtCompany                 4327 non-null   int64
 19  YearsSinceLastPromotion        4327 non-null   int64
 20  YearsWithCurrManager           4327 non-null   int64
 21  EnvironmentSatisfaction        4327 non-null   float64
 22  JobSatisfaction                4327 non-null   float64
 23  WorkLifeBalance                4327 non-null   float64
 24  JobInvolvement                 4327 non-null   int64
 25  PerformanceRating              4327 non-null   int64
 26  Education_Label                4327 non-null   object
 27  JobSatisfaction_Label          4327 non-null   object
 28  EnvironmentSatisfaction_Label  4327 non-null   object
 29  WorkLifeBalance_Label          4327 non-null   object
 30  PerformanceRating_Label        4327 non-null   object
dtypes: float64(5), int64(14), object(12)
memory usage: 1.0+ MB

In [6]:
df.describe()

,Age,DistanceFromHome,Education,EmployeeID,JobLevel,MonthlyIncome,NumCompaniesWorked,PercentSalaryHike,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,YearsAtCompany,YearsSinceLastPromotion,YearsWithCurrManager,EnvironmentSatisfaction,JobSatisfaction,WorkLifeBalance,JobInvolvement,PerformanceRating
count,4327.000000,4327.000000,4327.000000,4327.000000,4327.000000,4327.000000,4327.000000,4327.000000,4327.000000,4327.000000,4327.000000,4327.000000,4327.000000,4327.000000,4327.000000,4327.000000,4327.000000,4327.000000,4327.000000
mean,36.916570,9.186966,2.913797,2208.812803,2.067021,65029.244280,2.689161,15.210307,0.794777,11.272244,2.796626,7.020337,2.185810,4.128264,2.724520,2.724983,2.761498,2.727987,3.153686
std,9.143345,8.092618,1.024080,1273.370663,1.107342,46976.222828,2.491730,3.658903,0.853017,7.779457,1.288936,6.140673,3.227776,3.563110,1.092955,1.101498,0.706921,0.711318,0.360689
min,18.000000,1.000000,1.000000,1.000000,1.000000,10090.000000,0.000000,11.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000,1.000000,3.000000
25%,30.000000,2.000000,2.000000,1105.500000,1.000000,29260.000000,1.000000,12.000000,0.000000,6.000000,2.000000,3.000000,0.000000,2.000000,2.000000,2.000000,2.000000,2.000000,3.000000
50%,36.000000,7.000000,3.000000,2212.000000,2.000000,49360.000000,2.000000,14.000000,1.000000,10.000000,3.000000,5.000000,1.000000,3.000000,3.000000,3.000000,3.000000,3.000000,3.000000
75%,43.000000,14.000000,4.000000,3312.500000,3.000000,83805.000000,4.000000,18.000000,1.000000,15.000000,3.000000,9.000000,3.000000,7.000000,4.000000,4.000000,3.000000,3.000000,3.000000
max,60.000000,29.000000,5.000000,4409.000000,5.000000,199990.000000,9.000000,25.000000,3.000000,40.000000,6.000000,40.000000,15.000000,17.000000,4.000000,4.000000,4.000000,4.000000,4.000000

In [14]:
df.describe(include='object')

,Attrition,BusinessTravel,Department,EducationField,Gender,JobRole,MaritalStatus,Education_Label,JobSatisfaction_Label,EnvironmentSatisfaction_Label,WorkLifeBalance_Label,PerformanceRating_Label
count,4327,4327,4327,4327,4327,4327,4327,4327,4327,4327,4327,4327
unique,2,3,3,6,2,9,3,5,4,4,4,2
top,No,Travel_Rarely,Research & Development,Life Sciences,Male,Sales Executive,Married,Bachelor,Very High,High,Better,Excellent
freq,3626,3070,2824,1778,2590,959,1981,1684,1342,1330,2630,3662

In [18]:
df.isnull().sum()

Age                              0
Attrition                        0
BusinessTravel                   0
Department                       0
DistanceFromHome                 0
Education                        0
EducationField                   0
EmployeeID                       0
Gender                           0
JobLevel                         0
JobRole                          0
MaritalStatus                    0
MonthlyIncome                    0
NumCompaniesWorked               0
PercentSalaryHike                0
StockOptionLevel                 0
TotalWorkingYears                0
TrainingTimesLastYear            0
YearsAtCompany                   0
YearsSinceLastPromotion          0
YearsWithCurrManager             0
EnvironmentSatisfaction          0
JobSatisfaction                  0
WorkLifeBalance                  0
JobInvolvement                   0
PerformanceRating                0
Education_Label                  0
JobSatisfaction_Label            0
EnvironmentSatisfaction_Label    0
WorkLifeBalance_Label            0
PerformanceRating_Label          0
dtype: int64

In [17]:
df.duplicated().sum()

np.int64(0)

In [19]:
(df.isnull().sum()/len(df))*100

Age                              0.0
Attrition                        0.0
BusinessTravel                   0.0
Department                       0.0
DistanceFromHome                 0.0
Education                        0.0
EducationField                   0.0
EmployeeID                       0.0
Gender                           0.0
JobLevel                         0.0
JobRole                          0.0
MaritalStatus                    0.0
MonthlyIncome                    0.0
NumCompaniesWorked               0.0
PercentSalaryHike                0.0
StockOptionLevel                 0.0
TotalWorkingYears                0.0
TrainingTimesLastYear            0.0
YearsAtCompany                   0.0
YearsSinceLastPromotion          0.0
YearsWithCurrManager             0.0
EnvironmentSatisfaction          0.0
JobSatisfaction                  0.0
WorkLifeBalance                  0.0
JobInvolvement                   0.0
PerformanceRating                0.0
Education_Label                  0.0
JobSatisfaction_Label            0.0
EnvironmentSatisfaction_Label    0.0
WorkLifeBalance_Label            0.0
PerformanceRating_Label          0.0
dtype: float64

In [35]:
float_cols = [
    'NumCompaniesWorked',
    'TotalWorkingYears',
    'EnvironmentSatisfaction',
    'JobSatisfaction',
    'WorkLifeBalance'
]

df[float_cols] = df[float_cols].astype(int)

In [39]:
(df['YearsSinceLastPromotion'] > df['YearsAtCompany']).sum()

np.int64(0)

In [40]:
(df['YearsWithCurrManager'] > df['YearsAtCompany']).sum()

np.int64(0)

In [42]:
df['EmployeeID'].nunique(), len(df)

(4327, 4327)

In [31]:
df['Department'].unique()

array(['Sales', 'Research & Development', 'Human Resources'], dtype=object)

In [24]:
df['JobRole'].unique()

array(['Healthcare Representative', 'Research Scientist',
       'Sales Executive', 'Human Resources', 'Research Director',
       'Laboratory Technician', 'Manufacturing Director',
       'Sales Representative', 'Manager'], dtype=object)

In [25]:
df['Gender'].unique()

array(['Female', 'Male'], dtype=object)

In [26]:
df['MaritalStatus'].unique()

array(['Married', 'Single', 'Divorced'], dtype=object)

In [27]:
df['Department'].value_counts()

Department
Research & Development    2824
Sales                     1315
Human Resources            188
Name: count, dtype: int64

In [32]:
df['JobRole'].value_counts()

JobRole
Sales Executive              959
Research Scientist           863
Laboratory Technician        760
Manufacturing Director       428
Healthcare Representative    381
Manager                      300
Sales Representative         244
Research Director            238
Human Resources              154
Name: count, dtype: int64